#!/usr/bin/env node
import { writeFile, access } from 'node:fs/promises'
import { SchemaIntrospector } from './schema/introspect.js'
import type { TableInfo } from './schema/types.js'

const USAGE = `usage: plainql init --url <database url> [--out plainql.config.ts] [--force]

  --url    postgres://…, mysql://… or a SQLite path (also read from DATABASE_URL)
  --out    where to write the config (default: plainql.config.ts)
  --force  overwrite an existing file`

const SENSITIVE = /password|passwd|secret|token|api_key|apikey|private_key|hash|salt|ssn|credit_card|card_number|iban/i
const MASKABLE = /^(phone|phone_number|mobile|email|e_mail)$/i

async function main(argv: string[]): Promise<number> {
  const [command, ...rest] = argv
  if (command !== 'init') {
    console.error(USAGE)
    return command === '--help' || command === '-h' ? 0 : 2
  }

  const args = parse(rest)
  const url = args.url ?? process.env.DATABASE_URL
  if (!url) {
    console.error('plainql init: pass --url or set DATABASE_URL\n\n' + USAGE)
    return 2
  }
  const out = args.out ?? 'plainql.config.ts'

  if (!args.force && await exists(out)) {
    console.error(`plainql init: ${out} already exists — pass --force to overwrite`)
    return 1
  }

  const schema = new SchemaIntrospector({ url })
  await schema.connect()
  const context = schema.getContext()
  await schema.disconnect()

  await writeFile(out, render(context.tables))
  console.log(`plainql init: wrote ${out} with ${context.tables.length} tables (${context.dialect})`)
  return 0
}

function parse(argv: string[]): { url?: string; out?: string; force: boolean } {
  const args: { url?: string; out?: string; force: boolean } = { force: false }
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === '--url') args.url = argv[++i]
    else if (arg === '--out') args.out = argv[++i]
    else if (arg === '--force') args.force = true
    else {
      console.error(`plainql init: unknown argument ${arg}\n\n${USAGE}`)
      process.exit(2)
    }
  }
  return args
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

// The connection string is never written out: it may carry a password.
function render(tables: TableInfo[]): string {
  const lines = [
    `import { defineConfig } from 'plainql'`,
    '',
    '/**',
    ' * Generated by `plainql init`. Review every table before use:',
    ' *   - allow: which operations the model may run against it',
    ' *   - columns.hidden: never sent to the model, stripped from results',
    ' *   - columns.masked: returned redacted (last4 | partial)',
    ' *   - description / columns.hints: what the schema cannot say (enum values, JSON layout, units)',
    ' * Tables you do not list are fully allowed — set `allow: []` to remove one entirely.',
    ' */',
    'export default defineConfig({',
    '  connection: {',
    "    url: process.env.DATABASE_URL ?? '',",
    '    // readOnlyUrl: process.env.DATABASE_READONLY_URL',
    '  },',
    '',
    '  security: {',
    '    requireWhereClause: true,',
    "    onViolation: 'throw'",
    '  },',
    '',
    '  // Domain knowledge for the model: business terms, conventions, units.',
    "  context: '',",
    '',
    '  tables: {'
  ]

  tables.forEach((table, index) => {
    const hidden = table.columns.filter((column) => SENSITIVE.test(column.name)).map((column) => column.name)
    const masked = table.columns.filter((column) => MASKABLE.test(column.name)).map((column) => column.name)
    const rows = table.rowCount ?? 0

    lines.push(`    ${key(table.name)}: {`)
    lines.push(`      allow: ['SELECT'],`)
    if (hidden.length > 0 || masked.length > 0) {
      lines.push('      columns: {')
      if (hidden.length > 0) lines.push(`        hidden: [${hidden.map((name) => `'${name}'`).join(', ')}],`)
      if (masked.length > 0) {
        lines.push(`        masked: { ${masked.map((name) => `${key(name)}: 'partial'`).join(', ')} },`)
      }
      lines.push('      },')
    }
    lines.push(`      maxRows: ${rows > 10_000 ? 500 : 1000}`)
    lines.push(`    }${index < tables.length - 1 ? ',' : ''}`)
  })

  lines.push('  },', '', '  ai: {', "    provider: 'anthropic',", '    // apiKey defaults to ANTHROPIC_API_KEY', '  }', '})', '')
  return lines.join('\n')
}

function key(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

main(process.argv.slice(2)).then(
  (code) => process.exit(code),
  (error: unknown) => {
    console.error(`plainql: ${error instanceof Error ? error.message : String(error)}`)
    process.exit(1)
  }
)
